apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: ahmedevops/log_output:2.5
          envFrom:
            - configMapRef:
                name: log-env-config
          volumeMounts:
            - mountPath: /shared
              name: info-txt-volume
      volumes:
        - name: info-txt-volume
          configMap:
              name: info-config    # name of the configmap
              items:
                - key: info.txt    # the key to be used
                  path: info.txt    # the path
