apiVersion: apps/v1
kind: Deployment
metadata:
  name: course
spec:
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: ahmedevops/todo
